---
# tasks file for master
#Install atomic-openshift-utils
- name: Install atomic-openshift-utils package
  yum: pkg=atomic-openshift-utils state=present
  #TODO Configure DNS for each node

  #TODO Install and configure external docker-registry
  #TODO Modify Image Tags
  #TODO Push Images to Docker-registry
  #TODO Modify docker config, add registry to external registry
  #TODO Restart docker
  #TODO Restart master and node service
