---
- name: generation the hello_world.txt file
  template:
    src: templates/ocp-private.js
    dest: /etc/yum.repos.d/ocp-private.repo
- lineinfile:
    path: /etc/hosts
    line: "{{ rhel_yum_repo_hosts }}"
