---
- name: generation the ocp-private.repo file
  template:
    src: templates/ocp-private.js
    dest: /etc/yum.repos.d/ocp-private.repo
- name: add to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ rhel_yum_repo_hosts }}"
