---
- name: Install required packages
  yum: pkg={{ item }} state=present
  with_items:
   - wget 
   - git
   - net-tools
   - bind-utils
   - iptables-services
   - bridge-utils
   - bash-completion
   - vim
   - lrzsz
   - unzip
- name: Update base packages
  yum: pkg=* state=latest
