---
- name: Install required packages
  yum: pkg={{ item }} state=present
  with_items:
   - wget 
   - git
   - net-tools
   - bind-utils
   - iptables-services
   - bridge-utils
   - bash-completion
   - kexec-tools 
   - sos 
   - psacct
   - python-ipaddress
   - yum-utils
   - vim
   - docker
- name: Update base packages
  yum: pkg=* state=latest
