---
- name: start docker
  service:
    name=docker
    state=started
    enabled=yes
- name: start iptables
  service:
    name=iptables
    state=started
    enabled=yes
- name: stop firewalld
  service:
    name=firewalld
    state=stopped
    enabled=no
