---
- name: Install nfs-utils
  yum: pkg=nfs-utils state=present

- name: Ensure directories to export exist
  file: 
    path: "{{ item.strip().split()[0] }}" 
    state: directory
    mode: 0770
    owner: nfsnobody
    group: nfsnobody
  with_items: "{{ nfs_exports }}"

- name: Configure exports
  template:
    dest: /etc/exports.d/openshift-ansible.exports
    src: exports.j2
    owner: root
    group: root
    mode: 0644
  register: nfs_exports_copy

- name: Restart NFS immediately if exports are updated.
  service: 
    name: nfs-server
    state: restarted
  when: nfs_exports_copy.changed

- name: Ensure nfs is running.
  service: 
    name: nfs-server
    state: started 
    enabled: yes
  when: nfs_exports|length                                         

